settings:
  clusterName: eks-demo
  clusterEndpoint: "https://A4681986382B00FC5912756FF73A6362.gr7.eu-west-1.eks.amazonaws.com"
serviceAccount:
  name: "karpenter-controller-eks-demo"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::<aws-account-id>:role/karpenter-controller-eks-demo"
controller:
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
