apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot-m-nodepool
spec:
  template:
    metadata: 
      labels:
        instancegroup: spot-m-instancegroup
    spec:
      expireAfter: 336h
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot"]
      - key: eks.amazonaws.com/instance-category
        operator: In
        values: ["m"]
      taints:
        - key: instance-type
          value: "spot-m"
          effect: NoSchedule


