apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: default
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - image: k8s.gcr.io/e2e-test-images/echoserver:2.5
          name: demo-echo
          ports:
            - containerPort: 8080
      nodeSelector:
        instancegroup: spot-m-instancegroup
      tolerations:
        - key: "instance-type"
          operator: "Equal"
          value: "spot-m"
          effect: "NoSchedule"              
