route:
  enabled: true
  parentRef:
    gatewayName: hellorayo-gateway
    namespace: gateway
  hostnames:
    - bluegreen.dev.hellorayo.co.uk
  backendRef:
    rules:
    - backendRefs:
      - name: myapp-v1-bluegreen
        port: 8080
        weight: 1
    #   - name: myapp-v2-bluegreen
    #     port: 8080
    #     weight: 0
    # - backendRefs:
    #   - name: myapp-v3-bluegreen
    #     port: 8080
    #     weight: 1
    #   matches:
    #   - headers:
    #     - name: traffic
    #       type: Exact
    #       value: test
