---
apiVersion: v1
kind: Namespace
metadata:
  name: karpenter-testing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: karpenter-testing
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 5
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: nginx
        name: echoserver
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 64Mi
            cpu: 500m
          limits:
            memory: 64Mi
