apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: myappssecret
  namespace: default
spec:
  refreshInterval: 4h
  secretStoreRef:
    name: apps-secretstore
    kind: ClusterSecretStore
  target:
    name: newsecret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: apps/newsecret
      property: user

