apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::218687456330:role/apps-secrets
  name: apps-secrets
  namespace: kube-system
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: apps-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: apps-secrets
            namespace: kube-system
  conditions:
      - namespaces:
        - default
