apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysecretfromsecretsmanager
  namespace: default
spec:
  refreshInterval: 4h
  secretStoreRef:
    name: eks-secretstore
    kind: ClusterSecretStore
  target:
    name: mysecretink8s
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: eks/mysecret
      property: user
  # - secretKey: password
  #   remoteRef:
  #     key: eks/mysecret
  #     property: pass 
