apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: eks-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
  conditions:
      - namespaces:
        - default
        - cert-manager